
import React, { useState, useEffect, useRef } from 'react';
import { Wand2, Copy, RefreshCw, Send, Loader2, Save } from 'lucide-react';
import { generateMarketingContent } from '../services/geminiService';
import { ContentConfig, SavedItem } from '../types';

interface ContentGeneratorProps {
  initialTopic?: string;
}

const CACHE_KEY_DRAFT_CONFIG = 'meridian_draft_config';
const CACHE_KEY_DRAFT_CONTENT = 'meridian_draft_content';

const ContentGenerator: React.FC<ContentGeneratorProps> = ({ initialTopic = '' }) => {
  const [config, setConfig] = useState<ContentConfig>({
    style: 'Professional',
    tone: 'Enthusiastic',
    format: 'Twitter Thread',
    topic: '',
    keyPoints: ''
  });
  
  const [generatedContent, setGeneratedContent] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const hasAutoGenerated = useRef(false);

  // Load from cache on mount
  useEffect(() => {
    const cachedConfig = localStorage.getItem(CACHE_KEY_DRAFT_CONFIG);
    const cachedContent = localStorage.getItem(CACHE_KEY_DRAFT_CONTENT);

    if (cachedConfig) {
      try {
        const parsedConfig = JSON.parse(cachedConfig);
        // If initialTopic is provided and DIFFERENT from cached topic, we prioritize initialTopic (from dashboard)
        // Otherwise we load the cached config
        if (initialTopic && initialTopic !== parsedConfig.topic) {
           setConfig(prev => ({ ...prev, topic: initialTopic }));
        } else {
           setConfig(parsedConfig);
        }
      } catch (e) {
         if (initialTopic) setConfig(prev => ({ ...prev, topic: initialTopic }));
      }
    } else if (initialTopic) {
       setConfig(prev => ({ ...prev, topic: initialTopic }));
    }

    if (cachedContent) {
       // Only load content if we aren't about to overwrite it with a new auto-generate
       // We'll handle the logic in the auto-generate effect
       setGeneratedContent(cachedContent);
    }
  }, []);

  // Sync state to cache
  useEffect(() => {
     localStorage.setItem(CACHE_KEY_DRAFT_CONFIG, JSON.stringify(config));
  }, [config]);

  useEffect(() => {
     localStorage.setItem(CACHE_KEY_DRAFT_CONTENT, generatedContent);
  }, [generatedContent]);

  // Handle incoming prop change (initialTopic)
  useEffect(() => {
    if (initialTopic) {
       setConfig(prev => ({ ...prev, topic: initialTopic }));
    }
  }, [initialTopic]);

  // Auto-generate effect
  useEffect(() => {
    const autoGenerate = async () => {
      // Only auto-generate if we have a NEW topic from props that is different from what we might have cached,
      // or if we simply want to trigger on navigation.
      // Logic: If initialTopic exists, and we haven't run this once for this mount, AND not generating.
      if (initialTopic && !hasAutoGenerated.current && !isGenerating) {
        
        // CHECK: Is the cached content already matching this topic? If so, don't regen.
        // This is tricky. Let's just say if initialTopic is passed, we assume user wants fresh content for THAT topic.
        // But we check if the cached content "looks" like it belongs to this topic? No, simpler:
        
        // Use flag to prevent double execution
        hasAutoGenerated.current = true; 
        
        // If the topic passed in is essentially the same as what we have in config/cache, maybe skip?
        // But user might have clicked "Generate" on dashboard again.
        // Let's force generate to be responsive to the Dashboard action.
        await handleGenerate(initialTopic);
      }
    };

    autoGenerate();
  }, [initialTopic]);

  const handleGenerate = async (topicOverride?: string) => {
    const topicToUse = topicOverride || config.topic;
    if (!topicToUse) return;
    
    setIsGenerating(true);
    setIsSaved(false);
    // Use the latest config state, but override topic if provided
    const content = await generateMarketingContent({
        ...config,
        topic: topicToUse
    });
    setGeneratedContent(content);
    setIsGenerating(false);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedContent);
  };

  const saveToLibrary = () => {
    if (!generatedContent) return;
    
    const newItem: SavedItem = {
      id: crypto.randomUUID(),
      type: 'CONTENT',
      title: config.topic || 'Untitled Draft',
      content: generatedContent,
      createdAt: new Date().toISOString(),
      tags: [config.format, config.style]
    };

    const existing = localStorage.getItem('meridian_library');
    const library = existing ? JSON.parse(existing) : [];
    localStorage.setItem('meridian_library', JSON.stringify([...library, newItem]));
    setIsSaved(true);
    setTimeout(() => setIsSaved(false), 2000);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-[calc(100vh-140px)]">
      {/* Left Column: Configuration */}
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-2">
            <Wand2 className="text-primary" /> AI Content Generator
          </h2>
          <p className="text-slate-400 text-sm mt-1">Generate culturally-resonant Web3 content with your unique Writing DNA</p>
        </div>

        <div className="bg-surface border border-slate-800 rounded-xl p-6 space-y-4">
          <h3 className="text-sm font-semibold text-primary uppercase tracking-wider flex items-center gap-2">
            Writing DNA Setup
          </h3>
          
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1">
              <label className="text-xs text-slate-400">Content Style</label>
              <select 
                value={config.style}
                onChange={(e) => setConfig({...config, style: e.target.value})}
                className="w-full bg-slate-900 border border-slate-700 rounded-lg p-2.5 text-sm text-white focus:border-primary focus:outline-none"
              >
                <option>Professional</option>
                <option>Degen / Slang</option>
                <option>Educational</option>
                <option>Meme-centric</option>
              </select>
            </div>
            <div className="space-y-1">
              <label className="text-xs text-slate-400">Tone</label>
              <select 
                value={config.tone}
                onChange={(e) => setConfig({...config, tone: e.target.value})}
                className="w-full bg-slate-900 border border-slate-700 rounded-lg p-2.5 text-sm text-white focus:border-primary focus:outline-none"
              >
                <option>Enthusiastic</option>
                <option>Neutral / Objective</option>
                <option>Sarcastic</option>
                <option>Urgent (FOMO)</option>
              </select>
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-xs text-slate-400">Format</label>
            <select 
              value={config.format}
              onChange={(e) => setConfig({...config, format: e.target.value})}
              className="w-full bg-slate-900 border border-slate-700 rounded-lg p-2.5 text-sm text-white focus:border-primary focus:outline-none"
            >
              <option>Twitter Thread</option>
              <option>Single Tweet</option>
              <option>LinkedIn Post</option>
              <option>Blog Post Outline</option>
            </select>
          </div>
        </div>

        <div className="bg-surface border border-slate-800 rounded-xl p-6 space-y-4 flex-grow flex flex-col">
            <h3 className="text-sm font-semibold text-primary uppercase tracking-wider">Content Brief</h3>
            
            <div className="space-y-2">
                <label className="text-xs text-slate-400">Topic or News</label>
                <textarea 
                    value={config.topic}
                    onChange={(e) => setConfig({...config, topic: e.target.value})}
                    placeholder="e.g. Bitcoin ETF Approval Expected This Week..."
                    className="w-full h-24 bg-slate-900 border border-slate-700 rounded-lg p-3 text-sm text-white focus:border-primary focus:outline-none resize-none"
                />
            </div>

            <div className="space-y-2">
                <label className="text-xs text-slate-400">Key Points (Optional)</label>
                <textarea 
                    value={config.keyPoints}
                    onChange={(e) => setConfig({...config, keyPoints: e.target.value})}
                    placeholder="Add specific points or alpha to include..."
                    className="w-full h-24 bg-slate-900 border border-slate-700 rounded-lg p-3 text-sm text-white focus:border-primary focus:outline-none resize-none"
                />
            </div>

            <button 
                onClick={() => handleGenerate()}
                disabled={isGenerating || !config.topic}
                className="w-full mt-auto bg-primary hover:bg-cyan-400 text-slate-900 font-bold py-3 rounded-lg transition-colors flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
                {isGenerating ? (
                    <>
                        <Loader2 className="animate-spin" size={18} /> Generating...
                    </>
                ) : (
                    <>
                        <Send size={18} /> Generate Content
                    </>
                )}
            </button>
        </div>
      </div>

      {/* Right Column: Output */}
      <div className="bg-surface border border-slate-800 rounded-xl p-6 flex flex-col h-full">
        <div className="flex justify-between items-center mb-4">
            <h3 className="text-sm font-semibold text-white">Generated Draft</h3>
            <div className="flex gap-2">
                <button 
                    onClick={saveToLibrary}
                    disabled={!generatedContent || isSaved}
                    className={`p-2 rounded-lg transition-colors flex items-center gap-2 ${isSaved ? 'text-emerald-400 bg-emerald-400/10' : 'text-slate-400 hover:text-white hover:bg-slate-700'}`}
                    title="Save to Library"
                >
                    <Save size={18} /> {isSaved && <span className="text-xs font-medium">Saved</span>}
                </button>
                <button 
                    onClick={copyToClipboard}
                    disabled={!generatedContent}
                    className="p-2 hover:bg-slate-700 rounded-lg text-slate-400 hover:text-white transition-colors disabled:opacity-30"
                    title="Copy to clipboard"
                >
                    <Copy size={18} />
                </button>
                <button 
                     onClick={() => handleGenerate()}
                     disabled={isGenerating || !config.topic}
                     className="p-2 hover:bg-slate-700 rounded-lg text-slate-400 hover:text-white transition-colors disabled:opacity-30"
                     title="Regenerate"
                >
                    <RefreshCw size={18} />
                </button>
            </div>
        </div>

        <div className="flex-grow bg-slate-900 rounded-lg p-4 overflow-y-auto border border-slate-800 relative">
            {isGenerating ? (
                <div className="absolute inset-0 flex flex-col items-center justify-center text-primary/70 animate-pulse">
                    <Wand2 size={48} className="mb-4" />
                    <p className="text-sm">Meridian AI is crafting your content...</p>
                </div>
            ) : generatedContent ? (
                <pre className="whitespace-pre-wrap font-sans text-sm text-slate-300 leading-relaxed">
                    {generatedContent}
                </pre>
            ) : (
                <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-600">
                    <Wand2 size={48} className="mb-4 opacity-20" />
                    <p className="text-sm">Your generated content will appear here</p>
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default ContentGenerator;
